export const optionsCategory = [
  { value: 'Cómics', label: 'Cómics'},
  { value: 'Libros Autobiográficos', label: 'Libros Autobiográficos'},
  { value: 'Libros científicos', label: 'Libros científicos'},
  { value: 'Libros de Autoayuda', label: 'Libros de Autoayuda'},
  { value: 'Libros de Aventuras', label: 'Libros de Aventuras'},
  { value: 'Libros de Cuentos', label: 'Libros de Cuentos'},
  { value: 'Libros de deporte', label: 'Libros de deporte'},
  { value: 'Libros de Humor', label: 'Libros de Humor'},
  { value: 'Libros de la Segunda Guerra Mundial', label: 'Libros de la Segunda Guerra Mundial'},
  { value: 'Libros de marketing', label: 'Libros de marketing'},
  { value: 'Libros de salud', label: 'Libros de salud'},
  { value: 'Libros de suspense', label: 'Libros de suspense'},
  { value: 'Libros de videojuegos', label: 'Libros de videojuegos'},
  { value: 'Libros electrónicos gratuitos "Kindle"', label: 'Libros electrónicos gratuitos "Kindle"'},
  { value: 'Libros sociedad', label: 'Libros sociedad'},
  { value: 'Microrrelatos', label: 'Microrrelatos'},
  { value: 'Novela de culto', label: 'Novela de culto'},
  { value: 'Novela de no ficción', label: 'Novela de no ficción'},
  { value: 'Novela Histórica', label: 'Novela Histórica'},
  { value: 'Novela negra', label: 'Novela negra'},
  { value: 'Novelas', label: 'Novelas'},
  { value: 'Novelas Románticas', label: 'Novelas Románticas'},
]